name: CI Demo

on:
  push:
    branches:
      - main

jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello
        run: echo "Hello Umar! This is your first GitHub Action running successfully 🚀"